// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZerverBot.Model;

#nullable disable

namespace zerver_bot_rewrite.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20260807204704_CreateInvites")]
    partial class CreateInvites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZerverBot.Model.Arena.ElectionVote", b =>
                {
                    b.Property<decimal>("VoterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("VoterId");

                    b.ToTable("ElectionVotes");
                });

            modelBuilder.Entity("ZerverBot.Model.Arena.OstracismVote", b =>
                {
                    b.Property<decimal>("VoterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("VoterId");

                    b.ToTable("OstracismVotes");
                });

            modelBuilder.Entity("ZerverBot.Model.Invite", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("InviteId")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("ZerverBot.Model.Transaction", b =>
                {
                    b.Property<decimal>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RecipientId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("SenderId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InteractionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ZerverBot.Model.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
